apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # Must be empty for static provisioning
  volumeName: ebs-static # Name of the PV to bind to
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
# This PVC can now be used in a Pod to mount the EBS volume.

---
# Example Pod using the above PVC
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: "ebs-static-demo"
spec:
  nodeSelector:
    # this can be found using `kubectl get nodes --show-labels`
    topology.kubernetes.io/zone: us-east-1b # Ensure the Pod is scheduled in the same zone as the EBS volume
  containers:
    - name: nginx
      image: nginx
      # mount the PVC to a path inside the container
      volumeMounts:
        - name: persistent-storage
          mountPath: "/usr/share/nginx/html" # Mount path inside the container. This is where the EBS volume will be accessible.
          # whatever data is present in the above path, it will be stored in the EBS volume.
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-static
# This Pod will have the EBS volume mounted at /usr/share/nginx/html
# Any data written to this path will be stored in the EBS volume.

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: "ebs-static-demo"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
