kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-12345678 # Replace with your actual EFS File System ID
  directoryPerms: "700" # Permissions for the directories created
  gidRangeStart: "1000" # Starting GID for dynamic provisioning. GID means Group ID
  gidRangeEnd: "2000" # Ending GID for dynamic provisioning
  basePath: "/dynamic-provisioning" # Base path for dynamic provisioning
