apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # Use empty string for dynamic provisioning
# This PVC will dynamically bind to an available EFS volume.

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: "efs-dynamic-demo"
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-dynamic
# create the Pod which uses the above PVC to mount the EFS volume.

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: "efs-dynamic-demo"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
# This Service exposes the Pod using a LoadBalancer.
