kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx
  # Labels for the ReplicaSet
  labels:
    app: frontend
    tier: web
spec:
  # Number of desired pod replicas
  replicas: 3
  selector:
    # ReplicaSet use these labels to identify the pods for creating desired number of replicas
    matchLabels:
      app: frontend
      tier: web
  # Pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
